services:
  # Frontend application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Backend API and WebSocket service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes: 
      - script-data:/app/scripts
    environment:
      - NODE_ENV=production
      - MAX_SCRIPT_SIZE=10485760  # 10MB
      - MAX_EXECUTION_TIME=300    # 5 minutes
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  script-data:

